service: medimentor

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}

functions:
  api:
    handler: server.handler  # Points to `server.js`
    events:
      - http:
          path: analyze-symptoms
          method: post
      - http:
          path: analyze-symptoms
          method: get
    environment:
      NODE_ENV: production

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000